name: Build and Release

on:
  - push

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF##*/}
