name: test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.ref }}
          echo ci-${{ github.event.pull_request.number || github.ref }}
          echo ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}

      - name: sleep
        run: |
          sleep 3600
