name: test

on:
  pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.ref }}
          echo ci-${{ github.event.pull_request.number || github.ref }}

      - name: sleep
        run: |
          sleep 3600
