name: Release

on:
  push:
    paths:
      - 'rockspec/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract release name
        id: release_env
        shell: bash
        run: |
          title="${{ github.event.head_commit.message }}"
          re="^feat: release v*(\S+)"
          if [[ $title =~ $re ]]; then
              echo "##[set-output name=version;]${BASH_REMATCH[1]}"
          else
              exit 1
          fi

      - name: Print
        run: |
          echo ${{ steps.release_env.outputs.version }}
