name: Build and Release

on:
  pull_request

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.ref }}
          echo ci-${{ github.event.pull_request.number || github.ref }}
