name: Release-test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Tarball
        run: |
          git diff --name-only | xargs echo
          git diff --name-only ${{ github.base_ref }} ${{ github.event.pull_request.head.sha }} | xargs echo
