name: test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-18.04
        os_name:
          - linux_openresty
          - linux_openresty_1_17
          - linux_tengine
          - linux_apisix_master_luarocks
          - linux_apisix_current_luarocks
          - linux_openresty_mtls

    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.ref }}
          echo ci-${{ github.event.pull_request.number || github.ref }}
          echo ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
          echo ${{ github.event.pull_request.number || github.ref }}

      - name: sleep
        run: |
          sleep 3600
